sudo: false
language: go
go:
# Needs strings.Builder, which didn't exist in 1.9
#  - "1.9"
  - "1.10"
  - "1.11"
  - tip
env:
  - GOOS=linux GOARCH=amd64
  - GOOS=linux GOARCH=arm
  - GOOS=windows GOARCH=amd64
  - GOOS=darwin GOARCH=amd64
